<?php
include ('database.php');
$ins_1=("insert into courses (c_name,c_hours) values ('Data Structure','18 h'),
						     ('File Organization','21 h'),
                                                     ('Math 3','18 h'),
                                                     ('Discrete Structure','15 h'),
                                            	     ('Network Programming','24 h'),
                                            	     ('Advanced Database','21 h'),
                                             	     ('Web Programming','21 h'),
                                            	     ('Software Development','24 h'),
                                            	     ('Algorithms','21 h'),
                                                     ('Artificial Intelligence','21 h'),
                                            	     ('C++','24 h'),
                                            	     ('Java','24 h'),
                                            	     ('C#','24 h'),
						     ('Data Minning','18 h'),
                                            	     ('Software Enineering','18 h');");

$db->MyExec($ins_1);

$ins_2=("insert into tas (ta_name,ta_phone,ta_email,ta_cID) values ('Ahmed Ali',01012345789,'a_ali@gmail.com',1),
			                                  ('Islam Fekry',01224587965,'i_fek@gmail.com',1),
                                                          ('Yomna Mohamed',01115200133,'y_mohmd@gmail.com',1),
                                                          ('Mohamed Sadeq',01226542315,'M_sdq@gmail.com',2),
                                                          ('Ali Mahmoud',01226635548,'a_mahm@gmail.com',2),
                                                          ('Aya Salah',01226465551,'a_slah@gamil.com',2),
                                                          ('Lobna Alaa',01113300011,'lbna_a@gmail.com',3),
                                                          ('Islam Tareq',01114569873,'i_tarq@gmail.com',3),
                                                          ('Mahmoud Farouq',01064645956,'m_froq@gmail.com',3),
                                                          ('Aya AbdElrahim',012233221101,'aya_abdo@gmail.com',4),
                                                          ('Ahmed Samy',01000778494,'a_samy@gmail.com',4),
                                                          ('Moaaz Tareq',01224433577,'m_trq',4),
                                                          ('Ahmed Lotfy',01006535631,'a_lot@gmail.com',5),
                                                          ('Rady AbdEllatif',01115454645,'r_abdo@gmail.com',5),
                                                          ('Sally Salah',010066113345,'sa_lah@gamil.com',5),
                                                          ('Mohamed Mostafa',01005469821,'m_most@gmail.com',6),
                                                          ('Nourhan Hassan',01225120130,'nor_hasn@gmail.com',6),
                                                          ('Abdelrahman Walid',01114343156,'a_walid@gmail.com',6),
                                                          ('Omar Fawzy',01224565412,'o_fwzy@gmail.com',7),
                                                          ('Moamen Mostafa',01004987534,'m_mostafaaa@gmail.com',7),
                                                          ('Reham Othman',01114754785,'r_oth@gmail.com',7),
                                                          ('Ahmed Ramzy',01000793451,'ahm_ram@gmail.com',8),
                                                          ('Abdallah Tawfiq',01119523164,'a_taawfeeq@gamil.com',8),
                                                          ('Noha Masoud',01008494846,'n_mas@gmail.com',8),
                                                          ('Ehab Mohamed',01226549314,'e_moh@gmail.com',9),
                                                          ('Islam Serag',01006393936,'islm_s@gmail.com',9),
                                                          ('Hamdy AbdElalim',01114131215,'ham_abdo@gmail.com',9),
                                                          ('Rehab Abdallah',01112030510,'r_abdo@gmail.com',10),
                                                          ('Khalid Mortada',01117852463,'kh_mortda@gmail.com',10),
                                                          ('Soha Mohamed',01225462134,'soo_m@gmail,com',10),
                                                          ('Lamiaa Ahmed',01114236154,'Lam_aa@gamil.com',11),
                                                          ('Nahed Alaa',01116261340,'nona_al@gmail.com',11),
                                                          ('Mostafa Ahmed',01227948759,'m_ahmd@gmail.com',11),
                                                          ('Mayar Mohamed',01228787945,'myr_mhmd@gmail,com',12),
                                                          ('Ramzy Khaled',01113636463,'r_khld@gmail.com',12),
                                                          ('Shimaa Khaled',01115423131,'shima_khld@gmail.com',12),
                                                          ('Asmaa saber',01114574741,'asma_sa@gmail.com',13),
                                                          ('Morad Abd-Elhamid',01114455879,'m_abdmid@gmail.com',13),
                                                          ('Sahar Mazen',01000878784,'shr_m@gmail.com',13),
                                                          ('Ismail Hasan',01225300012,'is_hsn@gmail.com',14),
                                                          ('Alaa Erfan',01015975382,'a_erfn@gmail.com',14),
                                                          ('Tasbeeh Samy',01114999953,'t_samy@gmail.com',14),
                                                          ('Fatma Mansour',01225111033,'f_m@gmail.com',15),
                                                          ('Omar Mazen',01045556694,'o_maz@gmail.com',15),
                                                          ('Adel Othman',01114568795,'a_othm@gmail.com',15);");

$db->MyExec($ins_2);
?>

